name: OverKY
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6314367277082056
title: Over Kentucky with a Flying Camera
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f4f5fb'
    - '#1c2e1a'
    - '#296126'
    - '#a4ada2'
  brandStrength: 0
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
