name: OverKY
favicon: null
layout_spectrum: 0.23927
typography_spectrum: 0.38251
title: Over Kentucky with a Flying Camera
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce2f2'
    - '#6a82ad'
    - '#899bc2'
    - '#bac6e5'
    - '#455f87'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
