name: OverKY
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38251
title: Over Kentucky with a Flying Camera
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#020202'
    - '#cfcfcf'
    - '#a7a7a7'
    - '#4b4b4b'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
